# Generated by Django 4.2.7 on 2023-12-01 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
