# Generated by Django 4.2.7 on 2023-12-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
    ]
